services:
  openlist:
    restart: always
    volumes:
      - '/etc/openlist:/opt/openlist/data'
    ports:
      - '5244:5244'
      - '5245:5245'
    user: '0:0'
    environment:
      - UMASK=022
      - TZ=Asia/Shanghai
    container_name: openlist
    image: 'openlistteam/openlist:latest@sha256:b1df5cd378dbd0b04f8978afb1e78f2fd19749e9c7a8eedb4d780e9ea6659f8e'
